version: '3.7'
services:

  node:
    image: sailsconf:node-app
    depends_on:
      - mysql
    entrypoint: node app.js
    env_file:
      - .env
    volumes:
      - .:/srv

  node-worker:
    image: sailsconf:node-app
    volumes:
      - .:/srv
    working_dir: /srv/integration-tests

  mysql:
    image: mariadb:10.2
    restart: always
    expose:
      - '3306'
    ports:
      - '3308:3306'
#    volumes:
#      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sailsconf
