version: '3.7'
services:

  node:
    image: ghcr.io/actuallyconnor/sailsconf:latest
    entrypoint: NODE_ENV=production node app.js
    expose:
      - 1337
    ports:
      - '1337:1337'
    working_dir: /srv
